spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AYCPQ1mTLi95TRhsEJdQgQo6zJcfeEOH5vfrNw+b6HTWkw76CFkNFZ2Rv2mTA8NuZy96TVLVG4++xrWWDwunpaJg1X9Zry/Ug43sHc63UJSGqzQbwjQWxXfWU8y6nmTi86EfCh9UwKU3NQ/wJYNPT/kd5lrNPClEIOHBGtM/UGlWcWXAK7FTz9hTcVRoLkn27wC7tWak+NsJ5k80ysvg1gxdTcqzWDvKVVy5D6GTjLrmOUJKVX8PPZuDedUMtsZK6gknSVUlqKb+4skD+F2J2sCOvUIlWbVphBBme1lLjh/kBA9WZIxj94qBqsTJjwEoDZ+2NfoCsy8t31BCrGESeeMj5V0WDevZhcVxLOpOr8ncV9hMc7LKSDNBwBaOPeLxNu83ys84FAv1XMKaU54K66OmMsvvG/5T6DRCAoOs4f2MAiM/NjNE5SBYDTpw15HWEa/qvDjADrJq6+Z7RDK7U3sTAtLRFCTT2Jd5PtkcFe070u10+dmbYREBgf7ypLdgXoyKbeuLVt18u+82+RqkeJuBqXBgO6t/2C2It1cPnfu1Yg=='

token:
  expiration_time: 864000000
  secret: A54SxLl7R0pGXNxFkdtL5J6YwZ8+LSL1dLSl/aE8AUEYGq0sQjCvbwVCJ0dy1yTK0slEH6AlCevlXJ+DXvHeOw==

gateway:
  ip: 192.168.0.12

order_service:
  url: http://ORDER-SERVICE/order-serivce/%s/orders
  exception:
    orders_is_empty: User's orders is empty.
